name: jbang
version: 0.135.1
summary: Unleash the power of Java
description: |
  Unleash the power of Java.
  Use `jbang` to run java, jar, jsh or kt file(s) with automatic dependency fetching
  and immediate compilation and execution.

grade: stable
confinement: classic
base: core18
type: app

apps:
  jbang:
    command: bin/jbang

parts:
  jbang:
    plugin: dump
    source: https://github.com/jbangdev/jbang/releases/download/v0.135.1/jbang-0.135.1.tar
    source-checksum: sha256/307df3c8481d4121aca42fa35eaa040df2d31084e05fe706b636e990ed2b220a
    stage-packages:
      - curl
